# Generated by Django 3.2.3 on 2021-06-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombreServicio',
            field=models.CharField(max_length=100, verbose_name='Servicio'),
        ),
    ]
