# Generated by Django 3.2.3 on 2021-06-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210625_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefono'),
        ),
    ]
