# Generated by Django 3.2.3 on 2021-06-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210625_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
            ],
        ),
    ]
