# Generated by Django 3.2.3 on 2021-06-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
